openapi: 3.0.3
info:
  title: Mumble Link API
  description: OpenAPI spec for mumble link server and client
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  version: 1.0.0

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  schemas:
    Server:
      $ref: './schemas/server.yaml'
    Channel:
      $ref: './schemas/channel.yaml'
    Group:
      $ref: './schemas/group.yaml'
    User:
      $ref: './schemas/user.yaml'
    Error:
      $ref: './schemas/error.yaml'
security:
  - Bearer: []

paths:
  /servers:
    $ref: './paths/servers.yaml'
  /server/create:
    $ref: './paths/server.create.yaml'
  /server/{server_id}:
    $ref: './paths/server.server_id.yaml'
  /server/{server_id}/users:
    $ref: './paths/server.server_id.users.yaml'
  /server/{server_id}/user/{user_id}:
    $ref: './paths/server.server_id.user.user_id.yaml'
  /server/{server_id}/user/{user_id}/mute:
    $ref: './paths/server.server_id.user.user_id.mute.yaml'
  /server/{server_id}/user/{user_id}/unmute:
    $ref: './paths/server.server_id.user.user_id.unmute.yaml'
  /server/{server_id}/user/{user_id}/kick:
    $ref: './paths/server.server_id.user.user_id.kick.yaml'
  /server/{server_id}/user/{user_id}/ban:
    $ref: './paths/server.server_id.user.user_id.ban.yaml'
  /server/{server_id}/user/{user_id}/bans:
    $ref: './paths/server.server_id.user.user_id.bans.yaml'
  /server/{server_id}/user/{user_id}/move:
    $ref: './paths/server.server_id.user.user_id.move.yaml'
  /server/{server_id}/groups:
    $ref: './paths/server.server_id.groups.yaml'
  /server/{server_id}/group/create:
    $ref: './paths/server.server_id.group.create.yaml'
  /server/{server_id}/group/{group_id}:
    $ref: './paths/server.server_id.group.group_id.yaml'
  /server/{server_id}/channels:
    $ref: './paths/server.server_id.channels.yaml'
  /server/{server_id}/channel/create:
    $ref: './paths/server.server_id.channel.create.yaml'
  /server/{server_id}/channel/{channel_id}:
    $ref: './paths/server.server_id.channel.channel_id.yaml'